<a href="https://colab.research.google.com/github/SOUMYADEEP1805/bigdata/blob/main/numpylab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
test = [1,2,3]

In [ ]:
np.array(test)

array([1, 2, 3])

In [ ]:
arr = np.array(test)

In [ ]:
test1 = [[1,2,3],[4,5,6],[7,8,9]]
test1

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(test1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.zeros(3) 

array([0., 0., 0.])

In [ ]:
np.ones(3) 

array([1., 1., 1.])

In [ ]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
np.linspace(0,3,9)

array([0.   , 0.375, 0.75 , 1.125, 1.5  , 1.875, 2.25 , 2.625, 3.   ])

In [ ]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [ ]:
np.linspace(0,1,3,dtype=int)

array([0, 0, 1])

In [ ]:
np.random.rand(3)

array([0.8523049 , 0.32343884, 0.48182163])

In [ ]:
np.random.rand(3,3)

array([[0.48001535, 0.51244676, 0.56363353],
       [0.98775997, 0.8574043 , 0.1724245 ],
       [0.91198833, 0.69734079, 0.78018623]])

In [ ]:
np.random.randint(1,50)

47

In [ ]:
np.random.randint(1,50,10)

array([10, 44, 42, 35, 41, 18, 40, 23, 16, 20])

In [ ]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
ranint = np.random.randint(0,50,10)
ranint

array([38, 31, 38, 20, 20, 19, 13,  3,  7,  2])

In [ ]:
ranint.max()

38

In [ ]:
ranint.min()

2

In [ ]:
ranint.argmin()

9

In [ ]:
ranint.argmax()

0

In [ ]:
arr = arr.reshape(5,5)
arr.shape

(5, 5)

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr1 = np.random.randint(1,50,11)
arr1

array([24, 19, 38, 30, 25, 41, 19, 33, 36, 33, 30])

In [ ]:
arr1[0]

24

In [ ]:
arr1[0:4]

array([24, 19, 38, 30])

In [ ]:
arr[:] = 20
arr


array([[20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20]])

In [ ]:
arr1[arr1 >= 30]

array([38, 30, 41, 33, 36, 33, 30])

In [ ]:
arr1[arr1 > 30]

array([38, 41, 33, 36, 33])

In [ ]:
arr1[arr1 < 30]

array([24, 19, 25, 19])

In [ ]:
my_array = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/titanic.csv',delimiter=",")

In [ ]:
print (my_array)

     PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0              1         0       3  ...   7.2500   NaN         S
1              2         1       1  ...  71.2833   C85         C
2              3         1       3  ...   7.9250   NaN         S
3              4         1       1  ...  53.1000  C123         S
4              5         0       3  ...   8.0500   NaN         S
..           ...       ...     ...  ...      ...   ...       ...
886          887         0       2  ...  13.0000   NaN         S
887          888         1       1  ...  30.0000   B42         S
888          889         0       3  ...  23.4500   NaN         S
889          890         1       1  ...  30.0000  C148         C
890          891         0       3  ...   7.7500   NaN         Q

[891 rows x 12 columns]


In [ ]:
print (my_array.head(5))

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]


In [ ]:
my_array.to_csv('/content/drive/MyDrive/Colab Notebooks/my_pandas_dataframe.csv', index=False)

In [ ]:
y=my_array.to_csv('/content/drive/MyDrive/Colab Notebooks/my_pandas_dataframe1.csv', index=False, columns=['PassengerId','Survived'])

In [ ]:
y=my_array.to_csv('/content/drive/MyDrive/Colab Notebooks/my_pandas_dataframe2.csv', index=False,columns=['PassengerId','Survived'])

In [ ]:
yy=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/my_pandas_dataframe2.csv')

In [ ]:
print (yy.head(5))

   PassengerId  Survived
0            1         0
1            2         1
2            3         1
3            4         1
4            5         0


In [ ]:
#How to save a NumPy array to a .csv file in Python
a_np_array = np.array([[1, 2, 3], [4, 5, 6]],dtype=int)
a_np_array

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.savetxt("/content/drive/MyDrive/Colab Notebooks/output.csv", a_np_array, delimiter=",")

In [ ]:
#Load File using numpy
y = np.loadtxt("/content/drive/MyDrive/Colab Notebooks/output.csv",dtype=str)

In [ ]:
#how to skip the row in numpy
my= np.loadtxt('/content/drive/MyDrive/Colab Notebooks/2021.csv',delimiter=",", skiprows=1)

In [ ]:
print (my[0:5,:])

[[ 1. 10. 22.]
 [ 2. 11. 23.]
 [ 3. 12. 24.]
 [ 4. 13. 25.]
 [ 5. 14. 26.]]


In [ ]:
#store only 5 vaules 
np.savetxt("/content/drive/MyDrive/Colab Notebooks/saved_numpy_data_1.csv", my[0:5,:], delimiter=",")

In [ ]:
# Creating a numpy array
a=np.array([1,2,3,4,5])

In [ ]:
type(a)

numpy.ndarray